name: Publish Page

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install depends
        run: npm install

      - name: Build project
        run: npm run build

      - name: Publish
        run: npm run deploy
